<?php $getPage = $_GET['page']; ?>
<!--Navbar Start-->
<div class="col-md-12 pull-left b2s-post-menu del-padding-left">
    <a class="btn btn-<?php echo ($getPage == 'blog2social-post') ? 'primary' :'link'; ?> b2s-post-btn" href="admin.php?page=blog2social-post"><?php _e('All Posts','blog2social') ?></a>
    <a class="btn btn-<?php echo ($getPage == 'blog2social-sched') ? 'primary' :'link'; ?> b2s-post-btn" href="admin.php?page=blog2social-sched"><?php _e('Scheduled Posts','blog2social') ?></a>
    <a class="btn btn-<?php echo ($getPage == 'blog2social-publish') ? 'primary' :'link'; ?> b2s-post-btn" href="admin.php?page=blog2social-publish"><?php _e('Shared Posts','blog2social') ?></a>
</div>
<hr class="pull-left">

<div class="hidden-lg hidden-md hidden-sm filterShow"><a href="#" onclick="showFilter('show');return false;"><i class="glyphicon glyphicon-chevron-down"></i><?php _e('filter','blog2social') ?></a></div>
<div class="hidden-lg hidden-md hidden-sm filterHide"><a href="#" onclick="showFilter('hide');return false;"><i class="glyphicon glyphicon-chevron-up"></i><?php _e('filter','blog2social') ?></a></div>
<!--Navbar Ende-->